void reset(void);
void f_16C54(char *num);
void f_16E44(char *a, char *b);
void f_1A424(char *num, char *num2);
void f_1A438(char *a, char *b);
void f_1A460(char *a, char *b);
void num_abs(char *num);
void num_unk_1_1__(char *a, char *b);
void f_1AC6A(char *num);
void f_1AC7E(char *num);
void f_1AC92(char *num);
char f_1ADB6(char *num);
char num_cmplx_abs(char *num);
void f_1AFB8(char *num);
char f_1AFD8(char *num, char b);
char num_sign(char *num);
char num_cmp(char *num1, char *num2);
char get_numtype(char *num);
char num_fromdigit(char *dest, char digit);
void f_1B208(char *num);
void f_1B238(char *num);
char get_num_err_type(char *num);
void num_mulxp__(char *num, int exp);
int num_get_exp(char *num);
void f_1B378(char *num);
void num_trunc__(char *num);
void num_frombyte(char *num, char byte);
char num_to_byte(char *num);
void num_cpy_im(char *dest, char *src);
void num_cpy(char *dest, char *src);
